services:

  db:
    image: postgres:17
    restart: unless-stopped

    environment:
      POSTGRES_DB: cantina
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

    volumes:
      - cantina-data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d cantina"]
      interval: 5s
      timeout: 5s
      retries: 10


  backend:
    build:
      context: .
      dockerfile: Dockerfile

    restart: unless-stopped

    environment:
      DB_URL: jdbc:postgresql://db:5432/cantina
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_USERNAME: ${ADMIN_USERNAME}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}

    ports:
      - "8080:8080"

    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ../cantina-admin
      dockerfile: Dockerfile

    restart: unless-stopped

    ports:
      - "80:80"

    depends_on:
      - backend

volumes:
  cantina-data: