spring.application.name=cantina

jwt.secret=${JWT_SECRET}

spring.datasource.url=jdbc:postgresql://localhost:5432/cantina
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.open-in-view=false

spring.mvc.hiddenmethod.filter.enabled=true

spring.jpa.properties.hibernate.format_sql=true